# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('district_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='\u533a\u4ee3\u7801')),
                ('name', models.CharField(max_length=10, verbose_name='\u533a\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=30, null=True, verbose_name='\u7535\u8bdd')),
                ('duty', models.CharField(max_length=30, null=True, verbose_name='\u804c\u52a1')),
                ('channel', models.CharField(max_length=10, null=True, verbose_name='\u7535\u53f0\u4fe1\u9053')),
                ('call_sign', models.CharField(max_length=10, null=True, verbose_name='\u7535\u53f0\u547c\u53f7')),
                ('level', models.IntegerField(default=0, null=True)),
                ('role', models.IntegerField(default=0, null=True)),
                ('main_id', models.IntegerField(default=0, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_faculty', to='app_1.District')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='\u8def\u7ebf\u540d\u79f0')),
                ('start_place', models.CharField(max_length=50, null=True, verbose_name='\u8d77\u70b9\u5730\u540d')),
                ('end_place', models.CharField(max_length=50, null=True, verbose_name='\u7ec8\u70b9\u5730\u540d')),
                ('length', models.CharField(default='', max_length=10, verbose_name='\u8def\u7ebf\u957f\u5ea6')),
                ('sectionids', models.CharField(default='', max_length=400)),
                ('remark1', models.CharField(default='', max_length=100, null=True)),
                ('remark2', models.CharField(default='', max_length=100, null=True)),
                ('remark3', models.CharField(default='', max_length=100, null=True)),
                ('channel', models.CharField(default='1W', max_length=10, null=True)),
                ('call_sign', models.CharField(default='', max_length=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('chief', models.ManyToManyField(related_name='Faculty_Road_Chief', to='app_1.Faculty')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Districr_Road', to='app_1.District')),
                ('exec_chief_armed_poli', models.ManyToManyField(related_name='Faculty_Road_Exec_Chief_Armed_Poli', to='app_1.Faculty')),
                ('exec_chief_sub_bureau', models.ManyToManyField(related_name='Faculty_Road_Exec_Chief_Sub_Bureau', to='app_1.Faculty')),
                ('exec_chief_trans', models.ManyToManyField(related_name='Faculty_Road_Exec_Chief_Trans', to='app_1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='\u8def\u6bb5\u540d\u79f0')),
                ('start_place', models.CharField(max_length=50, null=True, verbose_name='\u8d77\u70b9\u5730\u540d')),
                ('end_place', models.CharField(max_length=50, null=True, verbose_name='\u7ec8\u70b9\u5730\u540d')),
                ('xy_coordinate', models.CharField(default='', max_length=1000)),
                ('remark1', models.CharField(default='', max_length=100, null=True)),
                ('remark2', models.CharField(default='', max_length=100, null=True)),
                ('remark3', models.CharField(default='', max_length=100, null=True)),
                ('channel', models.CharField(default='1W', max_length=10, null=True)),
                ('call_sign', models.CharField(default='', max_length=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('chief', models.ManyToManyField(related_name='Faculty_Section_Chief', to='app_1.Faculty')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_section', to='app_1.District')),
                ('exec_chief_armed_poli', models.ManyToManyField(related_name='Faculty_Section_Exec_Chief_Armed_Poli', to='app_1.Faculty')),
                ('exec_chief_sub_bureau', models.ManyToManyField(related_name='Faculty_Section_Exec_Chief_Sub_Bureau', to='app_1.Faculty')),
                ('exec_chief_trans', models.ManyToManyField(related_name='Faculty_Section_Exec_Chief_Trans', to='app_1.Faculty')),
                ('road', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Road_Section', to='app_1.Road')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startPlace', models.CharField(max_length=100)),
                ('endPlace', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=100)),
                ('roadids', models.CharField(default='', max_length=400)),
                ('submit_district', models.CharField(default='', max_length=20)),
                ('remark1', models.CharField(default='', max_length=100)),
                ('remark2', models.CharField(default='', max_length=100)),
                ('remark3', models.CharField(default='', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('district', models.ManyToManyField(related_name='District_Service', to='app_1.District')),
                ('road', models.ManyToManyField(related_name='Road_Service', to='app_1.Road')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5c97\u54e8\u540d\u79f0')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='\u5c97\u54e8\u7ecf\u7eac\u5ea6')),
                ('remark1', models.CharField(default='', max_length=100, null=True)),
                ('remark2', models.CharField(default='', max_length=100, null=True)),
                ('remark3', models.CharField(default='', max_length=100, null=True)),
                ('channel', models.CharField(default='1W', max_length=10, null=True)),
                ('call_sign', models.CharField(default='', max_length=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('chief', models.ManyToManyField(related_name='Faculty_Station_Chief', to='app_1.Faculty')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_station', to='app_1.District')),
                ('exec_chief_trans', models.ManyToManyField(related_name='Faculty_Station_Exec_Chief_Trans', to='app_1.Faculty')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Section_Station', to='app_1.Section')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set([('code', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'password')]),
        ),
        migrations.AlterUniqueTogether(
            name='serviceline',
            unique_together=set([('name', 'startPlace', 'endPlace', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set([('name', 'mobile', 'duty')]),
        ),
    ]
