# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='\u7535\u8bdd')),
                ('duty', models.CharField(max_length=30, null=True, verbose_name='\u804c\u52a1')),
                ('channel', models.CharField(max_length=10, null=True, verbose_name='\u7535\u53f0\u4fe1\u9053')),
                ('call_sign', models.CharField(max_length=10, null=True, verbose_name='\u7535\u53f0\u547c\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='\u8def\u7ebf\u540d\u79f0')),
                ('start_place', models.CharField(max_length=50, verbose_name='\u8d77\u70b9\u5730\u540d')),
                ('end_place', models.CharField(max_length=50, verbose_name='\u7ec8\u70b9\u5730\u540d')),
                ('start_point', models.CharField(max_length=50, verbose_name='\u8d77\u70b9\u7ecf\u7eac\u5ea6')),
                ('end_point', models.CharField(max_length=50, verbose_name='\u7ec8\u70b9\u7ecf\u7eac\u5ea6')),
                ('remark1', models.CharField(default='', max_length=100)),
                ('remark2', models.CharField(default='', max_length=100)),
                ('remark3', models.CharField(default='', max_length=100)),
                ('chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Road_Chief', to='app_1.Faculty')),
                ('exec_chief_armed_poli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Road_Exec_Chief_Armed_Poli', to='app_1.Faculty')),
                ('exec_chief_sub_bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Road_Exec_Chief_Sub_Bureau', to='app_1.Faculty')),
                ('exec_chief_trans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Road_Exec_Chief_Trans', to='app_1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='\u8def\u6bb5\u540d\u79f0')),
                ('start_place', models.CharField(max_length=50, verbose_name='\u8d77\u70b9\u5730\u540d')),
                ('end_place', models.CharField(max_length=50, verbose_name='\u7ec8\u70b9\u5730\u540d')),
                ('start_point', models.CharField(max_length=50, verbose_name='\u8d77\u70b9\u7ecf\u7eac\u5ea6')),
                ('end_point', models.CharField(max_length=50, verbose_name='\u7ec8\u70b9\u7ecf\u7eac\u5ea6')),
                ('remark1', models.CharField(default='', max_length=100)),
                ('remark2', models.CharField(default='', max_length=100)),
                ('remark3', models.CharField(default='', max_length=100)),
                ('chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Section_Chief', to='app_1.Faculty')),
                ('exec_chief_armed_poli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Section_Exec_Chief_Armed_Poli', to='app_1.Faculty')),
                ('exec_chief_sub_bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Section_Exec_Chief_Sub_Bureau', to='app_1.Faculty')),
                ('exec_chief_trans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Section_Exec_Chief_Trans', to='app_1.Faculty')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Road_Section', to='app_1.Road')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5c97\u54e8\u540d\u79f0')),
                ('location', models.CharField(max_length=50, verbose_name='\u5c97\u54e8\u7ecf\u7eac\u5ea6')),
                ('remark1', models.CharField(default='', max_length=100)),
                ('remark2', models.CharField(default='', max_length=100)),
                ('remark3', models.CharField(default='', max_length=100)),
                ('chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Station_Chief', to='app_1.Faculty')),
                ('exec_chief_trans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Station_Exec_Chief_Trans', to='app_1.Faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Section_Station', to='app_1.Section')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set([('name', 'mobile')]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('start_point', 'end_point')]),
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([('start_point', 'end_point')]),
        ),
    ]
