# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='main_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
