# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='mobile',
            field=models.CharField(max_length=30, null=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
