# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceline',
            unique_together=set([]),
        ),
    ]
