# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20180729_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='road',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
