# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20180820_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='main_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set([('name', 'mobile', 'duty', 'level', 'main_id', 'role')]),
        ),
    ]
