# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20180818_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='call_sign',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='channel',
            field=models.CharField(default='1W', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='call_sign',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='channel',
            field=models.CharField(default='1W', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='call_sign',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='channel',
            field=models.CharField(default='1W', max_length=10, null=True),
        ),
    ]
