# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20180818_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='call_sign',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='call_sign',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='call_sign',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
