# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20180730_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='chief',
        ),
        migrations.RemoveField(
            model_name='road',
            name='exec_chief_armed_poli',
        ),
        migrations.RemoveField(
            model_name='road',
            name='exec_chief_sub_bureau',
        ),
        migrations.RemoveField(
            model_name='road',
            name='exec_chief_trans',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chief',
        ),
        migrations.RemoveField(
            model_name='section',
            name='exec_chief_armed_poli',
        ),
        migrations.RemoveField(
            model_name='section',
            name='exec_chief_sub_bureau',
        ),
        migrations.RemoveField(
            model_name='section',
            name='exec_chief_trans',
        ),
        migrations.RemoveField(
            model_name='station',
            name='chief',
        ),
        migrations.RemoveField(
            model_name='station',
            name='exec_chief_trans',
        ),
    ]
