# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20180818_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([]),
        ),
    ]
