# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20180730_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty_Section_Chief', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='section',
            name='exec_chief_armed_poli',
            field=models.ManyToManyField(null=True, related_name='Faculty_Section_Exec_Chief_Armed_Poli', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='section',
            name='exec_chief_sub_bureau',
            field=models.ManyToManyField(null=True, related_name='Faculty_Section_Exec_Chief_Sub_Bureau', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='section',
            name='exec_chief_trans',
            field=models.ManyToManyField(null=True, related_name='Faculty_Section_Exec_Chief_Trans', to='app_1.Faculty'),
        ),
    ]
