# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20180730_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='chief',
            field=models.ManyToManyField(null=True, related_name='Faculty_Road_Chief', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='road',
            name='exec_chief_armed_poli',
            field=models.ManyToManyField(null=True, related_name='Faculty_Road_Exec_Chief_Armed_Poli', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='road',
            name='exec_chief_sub_bureau',
            field=models.ManyToManyField(null=True, related_name='Faculty_Road_Exec_Chief_Sub_Bureau', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='road',
            name='exec_chief_trans',
            field=models.ManyToManyField(null=True, related_name='Faculty_Road_Exec_Chief_Trans', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='station',
            name='chief',
            field=models.ManyToManyField(null=True, related_name='Faculty_Station_Chief', to='app_1.Faculty'),
        ),
        migrations.AddField(
            model_name='station',
            name='exec_chief_trans',
            field=models.ManyToManyField(null=True, related_name='Faculty_Station_Exec_Chief_Trans', to='app_1.Faculty'),
        ),
    ]
