# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20180818_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([]),
        ),
    ]
