# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_auto_20180818_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceline',
            name='submit_district',
            field=models.CharField(default='', max_length=20),
        ),
    ]
