# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_auto_20180730_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([('name', 'location')]),
        ),
    ]
