# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_auto_20180730_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='\u533a\u4ee3\u7801')),
                ('name', models.CharField(max_length=10, verbose_name='\u533a\u540d\u79f0')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set([('code', 'name')]),
        ),
        migrations.AddField(
            model_name='road',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Districr_Road', to='app_1.District'),
        ),
    ]
