# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_auto_20180730_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
