# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_section_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
