# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_station_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='chief',
        ),
        migrations.AddField(
            model_name='section',
            name='chief',
            field=models.ManyToManyField(null=True, related_name='Faculty_Section_Chief', to='app_1.Faculty'),
        ),
    ]
