# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_auto_20180801_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='length',
            field=models.CharField(default='', max_length=10, verbose_name='\u8def\u7ebf\u957f\u5ea6'),
        ),
    ]
