# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_road_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startPlace', models.CharField(max_length=100)),
                ('endPlace', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=100)),
                ('district', models.ManyToManyField(null=True, related_name='District_Service', to='app_1.District')),
            ],
        ),
        migrations.AlterField(
            model_name='road',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Districr_Road', to='app_1.District'),
        ),
        migrations.AlterField(
            model_name='section',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Road_Section', to='app_1.Road'),
        ),
        migrations.AlterField(
            model_name='station',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Section_Station', to='app_1.Section'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='road',
            field=models.ManyToManyField(null=True, related_name='Road_Service', to='app_1.Road'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceline',
            unique_together=set([('name', 'startPlace', 'endPlace')]),
        ),
    ]
