# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_auto_20180802_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceline',
            name='remark1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='remark2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='remark3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
