# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_auto_20180802_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='district_id',
            field=models.IntegerField(default=0),
        ),
    ]
