# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_account_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_faculty', to='app_1.District'),
        ),
        migrations.AddField(
            model_name='section',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_section', to='app_1.District'),
        ),
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_station', to='app_1.District'),
        ),
    ]
