# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_auto_20180807_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceline',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([('name', 'start_point', 'end_point')]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('name', 'start_point', 'end_point')]),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([('name', 'name', 'location')]),
        ),
    ]
