# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 07:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guard_line',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999L)])),
                ('type', models.CharField(max_length=1, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('team_group', models.CharField(max_length=20, null=True)),
                ('begins', models.CharField(max_length=64, null=True)),
                ('ends', models.CharField(max_length=64, null=True)),
                ('qwid', models.CharField(max_length=30, null=True)),
                ('begin_point', models.CharField(max_length=100, null=True)),
                ('end_point', models.CharField(max_length=100, null=True)),
                ('direction', models.CharField(max_length=10, null=True)),
                ('points', models.FileField(null=True, upload_to=b'')),
                ('tz', models.CharField(max_length=20, null=True)),
                ('line_id', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='guard_road',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999L)])),
                ('road_name', models.CharField(max_length=100, null=True)),
                ('road_begin', models.CharField(max_length=100, null=True)),
                ('road_end', models.CharField(max_length=100, null=True)),
                ('section_ids', models.CharField(max_length=4000, null=True)),
                ('remark1', models.CharField(max_length=100, null=True)),
                ('remark2', models.CharField(max_length=100, null=True)),
                ('remark3', models.CharField(max_length=100, null=True)),
                ('lineid', models.IntegerField(null=True)),
                ('roadlength', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sectionnum', models.IntegerField(null=True)),
                ('stationnum', models.IntegerField(null=True)),
                ('areaid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='guard_section',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999L)])),
                ('section_name', models.CharField(max_length=100, null=True)),
                ('section_begin', models.CharField(max_length=100, null=True)),
                ('section_end', models.CharField(max_length=100, null=True)),
                ('xycoordinate', models.CharField(max_length=4000, null=True)),
                ('station_ids', models.CharField(max_length=4000, null=True)),
                ('remark1', models.CharField(max_length=100, null=True)),
                ('remark2', models.CharField(max_length=100, null=True)),
                ('remark3', models.CharField(max_length=100, null=True)),
                ('roadid', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='guard_station',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999L)])),
                ('station_name', models.CharField(max_length=100, null=True)),
                ('xycoordinate', models.CharField(max_length=4000, null=True)),
                ('remark1', models.CharField(max_length=100, null=True)),
                ('remark2', models.CharField(max_length=100, null=True)),
                ('remark3', models.CharField(max_length=100, null=True)),
                ('sectionid', models.IntegerField(null=True)),
            ],
        ),
    ]
