# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard_road',
            name='sectionnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guard_road',
            name='stationnum',
            field=models.IntegerField(default=0),
        ),
    ]
