# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_guard_line_guard_road_guard_section_guard_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard_line',
            name='enabled',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='guard_road',
            name='enabled',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='guard_section',
            name='enabled',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='guard_station',
            name='enabled',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
