# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0003_auto_20180814_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard_line',
            name='vedio_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
