# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0003_auto_20180813_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard_admin',
            name='enabled',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='guard_line',
            name='enabled',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='guard_road',
            name='enabled',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='guard_section',
            name='enabled',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='guard_station',
            name='enabled',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
