# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 10:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0004_auto_20180813_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard_admin',
            name='uid',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999L)]),
        ),
        migrations.AddField(
            model_name='guard_line',
            name='uid',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999L)]),
        ),
        migrations.AddField(
            model_name='guard_road',
            name='uid',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999L)]),
        ),
        migrations.AddField(
            model_name='guard_section',
            name='uid',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999L)]),
        ),
        migrations.AddField(
            model_name='guard_station',
            name='uid',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999L)]),
        ),
        migrations.AlterField(
            model_name='guard_admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guard_line',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guard_road',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guard_section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guard_station',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
